apiVersion: http.keda.sh/v1alpha1
kind: HTTPScaledObject
metadata:
    name: nepa-server-scaler
    namespace: dev
spec:
    hosts: 
    - nepadoitguru.demo.agileguru.org
    - dev-server-router
    targetPendingRequests: 5
    scaleTargetRef:
        deployment: server-deployment
        service: server-service
        port: 8080
    replicas:
        min: 4
        max: 6