apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nepa-ingress
  namespace: dev
  labels:
    kcert.dev/ingress: "managed"
spec:
  ingressClassName: "nginx"
  tls:
  - hosts:
    - nepadoitguru.demo.agileguru.org
    secretName: nepadoit-agileguru-org
  rules:
  - host: nepadoitguru.demo.agileguru.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: client-service
            port: 
                number: 8888
      - path: /server
        pathType: Prefix
        backend:
          service: 
            name: server-service
            port: 
                number: 8080
      - path: /queue
        pathType: Prefix
        backend:
          service: 
            name: keda-router-admin
            port: 
                number: 9090          