apiVersion: v1
kind: Pod
metadata:
  name: docker-build-pod

  labels:
    some-label: some-label-value
spec:
  serviceAccountName: jenkins-admin
  # securityContext:
  #   runAsUser: 1000
  #   fsGroup: 1000
  containers:
  - name: jnlp
    env:
    - name: CONTAINER_ENV_VAR
      value: jnlp
  - name: google-cloud-sdk
    image: google/cloud-sdk:slim
    command:
    - gsutil
    args: ["cp", "gs://devops-353009-configurations/maven/settings.xml","~/.m2/settings.xml"]
  - name: docker
    image: docker:25.0.1
    imagePullPolicy: Always
    command:
    - cat
    tty: true
    volumeMounts:
    - mountPath: /var/run/docker.sock
      name: docker-sock
  restartPolicy: Never
  volumes:
   - name: docker-sock
     hostPath:
      path: /var/run/docker.sock
  