apiVersion: v1
kind: Pod
metadata:
  name: docker-build-pod

  labels:
    some-label: some-label-value
spec:
  serviceAccountName: jenkins-admin
  securityContext:
    runAsUser: 1000
    fsGroup: 1000
  containers:
  - name: jnlp
    env:
    - name: CONTAINER_ENV_VAR
      value: jnlp
  - name: maven
    image: maven:3.9.4-amazoncorretto-21
    command:
    - cat
    tty: true
  - name: docker
    image: docker:25.0.1
    imagePullPolicy: Always
    command:
    - cat
    tty: true
    volumeMounts:
    - mountPath: /var/run/docker.sock
      name: docker-sock
  restartPolicy: Never
  volumes:
   - name: docker-sock
     hostPath:
      path: /var/run/docker.sock
  