apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: server-only-example
  annotations:
    run.googleapis.com/launch-stage: BETA
spec:
  template:
    spec:
      containers:
      - image: agileguru/graalvmcloudnativeserver:main
        name: server
        ports:
        - name: http1
          containerPort: 8888
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi